import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // ローカルストレージから言語設定を取得
    const savedLanguage = localStorage.getItem('app-language')
    if (savedLanguage) {
      return savedLanguage
    }
    
    // ブラウザの言語設定を取得
    const browserLanguage = navigator.language || navigator.userLanguage
    return browserLanguage.startsWith('ja') ? 'ja' : 'en'
  })

  useEffect(() => {
    // 言語設定をローカルストレージに保存
    localStorage.setItem('app-language', language)
  }, [language])

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'ja' ? 'en' : 'ja')
  }

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || key
    
    // パラメータを置換: {name} → 実際の値
    if (params && typeof params === 'object') {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), paramValue)
      })
    }
    
    return text
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

// 翻訳データ
const translations = {
  ja: {
    // ヘッダー
    'menu.open': 'メニューを開く',
    'menu.title': 'メニュー',
    'menu.updates': '更新情報',
    'menu.pricing': '料金プラン',
    'menu.howToUse': '使い方',
    'menu.faq': 'FAQ',
    'menu.comingSoon': '準備中',
    'menu.myPage': 'マイページ',
    'menu.logout': 'ログアウト',
    'menu.login': 'ログイン',
    'menu.signup': '新規登録',
    'menu.plan': 'プラン',
    
    // 共通
    'common.goBack': '前に戻る',
    'common.returnToStart': '最初に戻る',
    
    // 軸選択
    'axis.title': '軸の設定',
    'axis.description': 'グラフの横軸（X軸）と縦軸（Y軸）に使用する列を選択してください',
    'axis.xAxisLabel': '横軸（X軸）',
    'axis.yAxisLabel': '縦軸（Y軸）',
    'axis.selectColumn': '列を選択',
    'axis.dataPreview': 'データプレビュー（最初の3行）',
    'axis.next': '次へ：単位とスケールを設定',
    
    // ホームページ
    'home.title': 'データからグラフを簡単作成',
    'home.subtitle': 'CSVファイルをアップロードして、美しいグラフを数秒で生成',
    'home.uploadButton': 'CSVファイルをアップロード',
    'home.orDragDrop': 'またはドラッグ&ドロップ',
    'home.reset': 'リセット',
    'home.download': 'ダウンロード',
    'home.analyzing': '分析中...',
    'home.resetDialog.title': '設定を破棄しますか？',
    'home.resetDialog.description': '現在の設定をすべて破棄して最初に戻ります。この操作は取り消せません。',
    'home.resetDialog.cancel': 'キャンセル',
    'home.resetDialog.ok': 'OK',
    
    // FileUpload
    'upload.title': 'ファイルをアップロード',
    'upload.description': 'CSV形式のファイルまたはExcelファイルをアップロードしてください',
    'upload.dropzone': 'ここにファイルをドロップ',
    'upload.or': 'または',
    'upload.selectFile': 'ファイルを選択',
    'upload.loading': '読み込み中...',
    'upload.error': 'エラー',
    'upload.sampleData': 'サンプルデータを使用',
    'upload.backToHome': 'ホームに戻る',
    'upload.supportedFormats': '対応形式: CSV, Excel (.xlsx, .xls)',
    'upload.maxSize': '最大サイズ: 10MB',
    'upload.sampleDataTitle': 'グラフ作成に最適なデータ構成の例',
    'upload.sampleDataDescription': 'どのような形式のファイルをアップロードすればスムーズにグラフが作成できるか、以下の例でご確認ください。',
    'upload.showSampleData': 'サンプルデータを表示',
    'upload.hideSampleData': 'サンプルデータを非表示',
    'upload.recommendedFormat': '推奨されるデータ構成例',
    'upload.sheetsFound': '個のシートが見つかりました',
    'upload.sheet': 'シート',
    'upload.rowsOfData': '行のデータ',
    'upload.delete': '削除',
    'upload.processing': 'ファイルを処理中...',
    
    // ChartDisplay
    'chart.title': 'グラフ',
    'chart.barChart': '棒グラフ',
    'chart.lineChart': '折れ線グラフ',
    'chart.pieChart': '円グラフ',
    'chart.downloadImage': 'グラフをダウンロード',
    'chart.reconfigure': '条件を変えて再生成',
    'chart.reset': 'リセット',
    'chart.showDataLabels': 'グラフにデータ値を表示',
    'chart.labelSize': 'ラベルサイズ',
    'chart.smaller': '小',
    'chart.larger': '大',
    'chart.settings': '設定',
    'chart.display': '表示',
    'chart.selectType': 'グラフの種類を選択',
    'chart.selectDescription': 'データに最適なグラフ形式を選んでください',
    'chart.dataLabels': 'データ値の表示',
    'chart.dataLabelsDescription': 'グラフ上にデータ値を表示します。ダウンロード時にも反映されます。',
    'chart.generatedChart': '生成されたグラフ',
    'chart.dataPoints': 'データポイント',
    'chart.dataSummary': 'データサマリー',
    'chart.dataCount': 'データ数',
    'chart.maximum': '最大値',
    'chart.minimum': '最小値',
    'chart.average': '平均値',
    'chart.median': '中央値',
    'chart.backToHome': 'ホームに戻る',
    'chart.auto': '自動',
    'chart.labelOverlapWarning': '💡 データ数が多い場合、ラベルが重なることがあります',
    
    // ChartInsights (AI解説)
    'insights.title': 'AI解説機能',
    'insights.description': 'グラフデータの傾向や特徴についてAIに質問できます',
    'insights.freeLimit': '（無料プラン: 5回/日）',
    'insights.standardLimit': '（50回/日）',
    'insights.proLimit': '（無制限）',
    'insights.proUnlimited': 'Pro - 無制限',
    'insights.upgradeTitle': 'アップグレードで回数制限を大幅拡張',
    'insights.currentLimit': '現在の利用制限: 5回/日',
    'insights.upgradeDescription': 'Standardプランなら50回/日、Proプランなら無制限で利用できます。',
    'insights.viewPlans': 'プランを見る',
    'insights.remainingUsage': '本日の残り利用回数',
    'insights.unlimited': '無制限でご利用いただけます',
    'insights.questionLabel': 'グラフについて質問してください',
    'insights.questionPlaceholder': '例：このデータの傾向を教えてください。最大値と最小値の差が大きい理由は何ですか？',
    'insights.submitHint': 'Enterキーで送信、Shift+Enterで改行',
    'insights.characterCount': '文字',
    'insights.analyzing': '分析中...',
    'insights.getInsights': 'AI解説を取得',
    'insights.error': 'エラー',
    'insights.resultTitle': 'AI解説結果',
    'insights.notesTitle': '💡 ご利用上の注意',
    'insights.noteUnlimited': 'Pro会員は無制限でご利用いただけます',
    'insights.noteDailyLimit': '1日あたり{limit}回まで利用可能です',
    'insights.noteReset': '利用回数は毎日0時（日本時間）にリセットされます',
    'insights.noteAccuracy': 'AIの回答は参考情報であり、完全な正確性を保証するものではありません',
    
    // 認証 (AuthModal)
    'auth.title': 'アカウント',
    'auth.description': 'ログインまたは新規登録してください',
    'auth.loginTab': 'ログイン',
    'auth.signupTab': '新規登録',
    'auth.email': 'メールアドレス',
    'auth.password': 'パスワード',
    'auth.name': '名前(任意)',
    'auth.namePlaceholder': '山田太郎',
    'auth.passwordConfirm': 'パスワード(確認)',
    'auth.passwordPlaceholder': '英数字と記号を含む12文字以上',
    'auth.passwordConfirmPlaceholder': 'パスワードを再入力',
    'auth.passwordRequirements': '大文字、小文字、数字、記号(!@#$など)を含む12文字以上',
    'auth.loggingIn': 'ログイン中...',
    'auth.loginButton': 'ログイン',
    'auth.registering': '登録中...',
    'auth.signupButton': '新規登録',
    'auth.forgotPassword': 'パスワードを忘れた場合',
    'auth.or': 'または',
    'auth.googleLogin': 'Googleでログイン',
    'auth.googleSignup': 'Googleで登録',
    'auth.error.emailInUse': 'このメールアドレスは既に登録されています',
    'auth.error.invalidEmail': 'メールアドレスの形式が正しくありません',
    'auth.error.userNotFound': 'ユーザーが見つかりません',
    'auth.error.wrongPassword': 'パスワードが間違っています',
    'auth.error.weakPassword': 'パスワードは英数字と記号を含む12文字以上で入力してください',
    'auth.error.popupClosed': 'ログインがキャンセルされました',
    'auth.error.recentLoginRequired': '再ログインが必要です',
    'auth.error.invalidCredential': '現在のパスワードが正しくありません',
    'auth.error.userDisabled': 'このアカウントは無効化されています',
    'auth.error.tooManyRequests': 'リクエストが多すぎます。しばらく待ってから再度お試しください',
    'auth.error.default': 'エラーが発生しました。もう一度お試しください',
    'auth.error.passwordMismatch': 'パスワードが一致しません',
    'auth.error.passwordInvalid': 'パスワードは以下を満たす必要があります: {errors}',
    
    // 料金プラン (Pricing)
    'pricing.pageTitle': 'グラフ作成がもっと快適に',
    'pricing.pageSubtitle': 'あなたに最適なプランを選んでください',
    'pricing.monthly': '月額',
    'pricing.yearly': '年額',
    'pricing.yearlyBadge': 'お得',
    'pricing.perMonth': '/月',
    'pricing.yearlyTotal': '年間 ¥{price} ({savings}%お得)',
    'pricing.popularChoice': '{percent}%のユーザーが選択',
    'pricing.perDay': '≈ 1日たった¥{price}',
    'pricing.processing': '処理中...',
    'pricing.currentPlan': '現在のプラン',
    'pricing.getStartedFree': '無料で始める',
    'pricing.upgrade': 'アップグレード',
    'pricing.planFree': 'Free',
    'pricing.planStandard': 'Standard',
    'pricing.planPro': 'Pro',
    'pricing.descFree': 'グラフ作成を始める',
    'pricing.descStandard': '本格的にグラフ分析',
    'pricing.descPro': 'プロフェッショナル向け',
    'pricing.badgePopular': '人気No.1',
    'pricing.feature.filesFree': 'ファイル保存：3個まで',
    'pricing.feature.filesStandard': 'ファイル保存：10個まで',
    'pricing.feature.filesPro': 'ファイル保存：無制限',
    'pricing.feature.aiFree': 'AIインサイト：月5回',
    'pricing.feature.aiStandard': 'AIインサイト：月50回',
    'pricing.feature.aiPro': 'AIインサイト：無制限',
    'pricing.feature.basicCharts': '基本的なグラフ作成機能',
    'pricing.feature.allCharts': '全グラフ作成機能',
    'pricing.feature.communitySupport': 'コミュニティサポート',
    'pricing.feature.prioritySupport': '優先サポート',
    'pricing.feature.dataExport': 'データエクスポート機能',
    'pricing.feature.apiAccess': 'API アクセス',
    'pricing.feature.apiAccessSoon': 'API アクセス（準備中）',
    'pricing.faqTitle': 'よくある質問',
    'pricing.faq1.question': 'プランの変更はいつでもできますか？',
    'pricing.faq1.answer': 'はい、いつでもプランの変更やキャンセルが可能です。プラン変更は即座に反映されます。',
    'pricing.faq2.question': 'AIインサイトとは何ですか？',
    'pricing.faq2.answer': 'AIがあなたのグラフデータを分析し、トレンドや特徴、改善点を自動的に提案する機能です。',
    'pricing.faq3.question': '無料プランから始められますか？',
    'pricing.faq3.answer': 'もちろんです！まずは無料プランでサービスをお試しいただき、必要に応じてアップグレードしてください。',
    'pricing.error.loginRequired': 'まずはアカウント登録が必要です',
    'pricing.error.priceIdNotFound': '価格IDが見つかりません',
    'pricing.error.checkoutFailed': 'エラーが発生しました: {message}',
    'pricing.error.paymentFailed': '決済ページの作成に失敗しました。もう一度お試しください。',
    
    // プライシング
    'pricing.title': '料金プラン',
    
    // MyPage
    'mypage.title': 'マイページ',
    'mypage.subtitle': 'アカウント情報とプラン詳細',
    'mypage.paymentSuccess.title': '🎉 決済が完了しました！',
    'mypage.paymentSuccess.description': '有料プランへのアップグレードが完了しました。すべての機能がご利用いただけます。',
    'mypage.profile.title': 'プロフィール',
    'mypage.profile.description': '基本的なアカウント情報',
    'mypage.profile.username': 'ユーザー名',
    'mypage.profile.notSet': '未設定',
    'mypage.profile.email': 'メールアドレス',
    'mypage.profile.registeredDate': '登録日',
    'mypage.profile.unknown': '不明',
    'mypage.plan.title': '現在のプラン',
    'mypage.plan.description': 'ご利用中のプラン情報',
    'mypage.plan.label': 'プラン',
    'mypage.plan.free': '無料プラン',
    'mypage.plan.standard': 'Standard プラン',
    'mypage.plan.pro': 'Pro プラン',
    'mypage.plan.premium': '有料プラン',
    'mypage.plan.upgrade': '有料プランにアップグレード',
    'mypage.plan.freeInfo': '<strong>無料プラン</strong>では基本機能をご利用いただけます。有料プランにアップグレードすると、以下の機能が利用可能になります:',
    'mypage.plan.feature1': 'グラフの高解像度エクスポート',
    'mypage.plan.feature2': 'カスタムテーマの作成',
    'mypage.plan.feature3': 'データ保存数の上限解除',
    'mypage.plan.feature4': '優先サポート',
    'mypage.settings.title': 'アカウント設定',
    'mypage.settings.description': 'アカウントの管理',
    'mypage.settings.editProfile': 'プロフィールを編集',
    'mypage.settings.changePassword': 'パスワードを変更',
    'mypage.settings.googleUserNote': 'Googleログインユーザーはパスワード変更できません',
    'mypage.settings.deleteAccount': 'アカウントを削除',
    
    // UpdatesPage
    'updates.title': '更新情報',
    'updates.9.title': '英語切り替え機能を実装',
    'updates.9.description': '日本語・英語の切り替えに対応しました。語順の違いを考慮して翻訳データ側で各言語の自然な語順を定義し、コンポーネント側は値を渡す構造にした方がいいのは勉強になった。',
    'updates.8.title': '利用規約とプライバシーポリシー、特商法ページ、Google Analyticsを導入',
    'updates.8.description': 'Stripe本番環境への移行準備として、利用規約とプライバシーポリシーを作成。有料プランを正式に提供できる環境を整えました。特定商取引法に基づく表記も最新情報に更新。アクセス解析のためGoogle Analyticsも導入。そして、広告ブロッカーによるブロックを回避するため、ファイル名をPrivacyPage.jsxとTermsPage.jsxに変更しています。',
    'updates.7.title': 'AIインサイト機能を実装',
    'updates.7.description': '有料会員向けの機能としてAIを使ったグラフおよびアップロードした表形式ファイルの分析ができるようにしました。APIを動作させる権限設定とかAPIテストのためのサーバー構築とか結構手こうずりましたがなんとか動作動いてよかった。料金ページも間もなく作ります。',
    'updates.6.title': 'アカウント削除機能とグラフのデータ値表示機能を実装',
    'updates.6.description': 'マイページからアカウントを安全に削除できるようになりました。2段階確認と再認証により誤操作を防止します。また、棒グラフと折れ線グラフでデータ値をグラフ上に表示できる機能を追加しました。データ数に応じてフォントサイズが自動調整され、手動での微調整も可能です。外部のシステムが絡むときは強制リロードちゃんとやろ...。',
    'updates.5.title': '細かい不便を改善',
    'updates.5.description': 'グラフ化したいデータが列の向きに並んでいるときにヘッダーの範囲選択をするとデータの向きが変更できない問題があったので修正しました。これでグラフ化したいデータが横向きに並んでいても問題なくグラフ化できます。',
    'updates.4.title': '括弧付きのデータも読み取れるように',
    'updates.4.description': 'データ内に括弧が含まれているときにその情報を保持したままグラフ化できるようになりました。あとグラフダウンロードするときに背景が透過で出力されて見づらい問題があったので白背景でダウンロードできるよう修正しました。',
    'updates.3.title': 'ログイン機能を実装しました',
    'updates.3.description': 'Firebase Authenticationを使って、メールアドレスとGoogleアカウントからのログインができるようにしました。',
    'updates.2.title': 'グラフ全体が見やすくなるようスライドバーを追加しました&グラフの色をスチールブルーベース系に変更しました',
    'updates.2.description': 'もっとグラフを見やすくなるように。',
    'updates.1.title': '更新情報ページを作りました',
    'updates.1.description': 'アプリの更新履歴をタイムライン形式で確認できるようになりました。',
    
    // DataRangeSelector
    'dataRange.titleData': 'データ領域を選択',
    'dataRange.titleHeader': '列ヘッダー領域を選択',
    'dataRange.descriptionData': 'グラフ化したいデータの範囲を指定してください。青色でハイライトされた領域が選択されます。',
    'dataRange.descriptionHeader': '項目名（列ヘッダー）が記載されている範囲を指定してください。複数行にまたがる場合は全て含めてください。',
    'dataRange.startRow': '開始行',
    'dataRange.endRow': '終了行',
    'dataRange.startCol': '開始列',
    'dataRange.endCol': '終了列',
    'dataRange.rangeInfo': '選択範囲：',
    'dataRange.rowCol': '{rows}行 × {cols}列',
    'dataRange.preview': 'データプレビュー',
    'dataRange.row': '行',
    'dataRange.showMore': 'さらに表示（残り{count}行）',
    'dataRange.confirmData': 'この範囲を使用してグラフを作成',
    'dataRange.confirmHeader': 'この範囲を列ヘッダーとして使用',
    'dataRange.backToStart': '最初に戻る',
    
    // SheetSelector
    'sheet.title': 'シートの選択',
    'sheet.description': 'このファイルには複数のシートが含まれています。グラフ化したいデータが含まれているシートを選択してください。',
    'sheet.available': '利用可能なシート（{count}個）',
    'sheet.number': 'シート {num}',
    'sheet.selected': '選択中：',
    'sheet.confirm': 'このシートで続ける',
    'sheet.back': '前に戻る',
    
    // HeaderRangeSelector
    'headerRange.title': 'ヘッダー領域の選択',
    'headerRange.description': '複数行にわたるヘッダーを指定できます。各列のヘッダーは自動的に結合されます。',
    'headerRange.headerStart': 'ヘッダー開始行',
    'headerRange.headerEnd': 'ヘッダー終了行',
    'headerRange.dataStart': 'データ開始行',
    'headerRange.rangeInfo': 'ヘッダー領域：行 {start} 〜 行 {end}（{count}行）',
    'headerRange.dataInfo': 'データ領域：行 {start} 以降',
    'headerRange.previewTitle': 'ヘッダーとデータのプレビュー',
    'headerRange.editHeaders': 'ヘッダー名の編集',
    'headerRange.editNote': 'クリックしてヘッダー名を編集できます',
    'headerRange.editWarning': '自動認識されたヘッダー名は自由に編集できます。複数行のヘッダーが結合されている場合など、必要に応じて修正してください。',
    'headerRange.column': '列 {num}',
    'headerRange.edited': '編集済',
    'headerRange.original': '元',
    'headerRange.columnName': 'の名前',
    'headerRange.dataRows': 'データ行',
    'headerRange.previewLabel': 'プレビュー（最初の5行）',
    'headerRange.previewNote': '設定を調整してプレビューを表示してください',
    'headerRange.hintsTitle': '使い方のヒント',
    'headerRange.hint1': 'ヘッダーが複数行にまたがる場合、終了行を指定してください',
    'headerRange.hint2': '各列のヘッダーは、指定範囲内で自動的に結合されます',
    'headerRange.hint3': 'データ開始行は、ヘッダー終了行の次の行以降にしてください',
    'headerRange.hint4': '例: 横軸「年」、縦軸「出生数」、ヘッダー行は、終了行以下、データ行は3以降',
    'headerRange.confirm': 'この設定で続ける',
    'headerRange.warningMultiRow': '複数行のヘッダーが結合されます',
    'headerRange.clickToEdit': 'クリックで編集',
    'headerRange.editButton': 'ヘッダーを編集',
    'headerRange.emptyWarningTitle': '空欄のヘッダーがあります',
    'headerRange.emptyWarningMessage': '空欄のヘッダーがあります。確認して編集してください。',
    'headerRange.checkSettings': '設定を確認してください',
    'headerRange.returnToStart': '最初に戻る',
    
    // DataOrientationSelector
    'orientation.title': 'データの向きを確認',
    'orientation.description': 'カテゴリ（項目名）が横方向と縦方向のどちらに並んでいるか確認してください。必要に応じてデータを転置（行列を入れ替え）できます。',
    'orientation.original': '元の向き',
    'orientation.transposed': '転置後',
    'orientation.previewOriginal': '元データのプレビュー',
    'orientation.previewTransposed': '転置後のプレビュー',
    'orientation.infoOriginal': 'カテゴリ：縦方向（現在）',
    'orientation.infoTransposed': 'カテゴリ：横方向（転置後）',
    'orientation.confirmOriginal': '元の向きで続ける',
    'orientation.confirmTransposed': '転置して続ける',
    'orientation.previewNotice': '※ 最初の5行のみ表示しています',
    'orientation.selectionHintsTitle': '💡 選び方のヒント',
    'orientation.hintOriginal': '元の向き：1行目が項目名（年度、月など）、2行目以降がデータの場合',
    'orientation.hintTransposed': '転置後：1列目が項目名、2列目以降がデータの場合',
    
    // ParenthesesInterpretationSelector
    'parentheses.title': '括弧付き数字の扱いについて',
    'parentheses.description': 'データに括弧で囲まれた数字が含まれています。この括弧の意味を選択してください。',
    'parentheses.examplesTitle': '検出された括弧付き数字の例',
    'parentheses.optionPositive': '括弧は単なる装飾（正の値として扱う）',
    'parentheses.optionNegative': '括弧はマイナスを意味する（負の値として扱う）',
    'parentheses.previewTitle': '変換プレビュー',
    'parentheses.previewOriginal': '元の値',
    'parentheses.previewConverted': '変換後',
    'parentheses.confirm': 'この設定で続ける',
    
    // SeparateHeaderSelector
    'separateHeader.title': '列ヘッダーの位置を確認',
    'separateHeader.description': '列ヘッダー（項目名）はデータ本体とは別の場所にありますか？',
    'separateHeader.guideTitle': 'どういう時に「はい」を選ぶ？',
    'separateHeader.guideExample': '例：統計表で、上部に列ヘッダー（給与所得者数、給与額など）があり、その下に「年次別」「事業所規模別」などの複数のデータセクションが縦に並んでいる場合。',
    'separateHeader.guideNote': '特定のセクション（例：事業所規模別のみ）でグラフを作りたい場合は「はい」を選択してください。',
    'separateHeader.selectedRange': '選択したデータ本体の範囲',
    'separateHeader.rows': '行： {start} 〜 {end} （{count}行）',
    'separateHeader.cols': '列： {start} 〜 {end} （{count}列）',
    'separateHeader.no': 'いいえ、同じ場所にあります',
    'separateHeader.yes': 'はい、別の場所にあります',
    
    // DataLabelRangeSelector
    'dataLabel.title': 'データ名（ラベル）列の選択',
    'dataLabel.description': '各データ行の名前（ラベル）が含まれる列を指定してください。複数列を選択すると結合されます。',
    'dataLabel.aboutTitle': 'このステップについて',
    'dataLabel.aboutText1': 'データの各行に付けられる名前（ラベル）が複数列に分かれている場合に使用します',
    'dataLabel.aboutExample': '例: C列に「個人」「2000万円未満」、D列に「その他法人」「合計」など',
    'dataLabel.aboutText2': '指定された列範囲内の空でないセルが自動的に結合されます',
    'dataLabel.aboutText3': 'データ名が1列のみの場合は「スキップ」してください',
    'dataLabel.guide': 'ラベル列とは？',
    'dataLabel.guideText': '行ごとのデータを識別するための名前が記載されている列です。',
    'dataLabel.example': '例：都道府県名、商品名、年月、カテゴリ名など',
    'dataLabel.autoMerge': '指定された列範囲内の空でない値が自動的に結合されます',
    'dataLabel.skipNote': 'データ名が1列のみの場合は「スキップ」してください',
    'dataLabel.labelStart': 'データ名開始列',
    'dataLabel.labelEnd': 'データ名終了列',
    'dataLabel.columnRange': '指定可能範囲',
    'dataLabel.headerName': '結合後のヘッダー名',
    'dataLabel.headerPlaceholder': '例：地域名',
    'dataLabel.headerNote': 'グラフの凡例などに使用されます',
    'dataLabel.rangeInfo': 'データ名列範囲：列 {start} 〜 列 {end}（{count}列）',
    'dataLabel.rowCount': 'データ行数：{count}行',
    'dataLabel.manualEdit': '手動編集：',
    'dataLabel.rowsEdited': '行',
    'dataLabel.autoMergeNote': '選択した列範囲内の空でない値が自動的に結合されます',
    'dataLabel.previewTitle': '結合後のデータ名プレビュー（全{count}行、空行は除外）',
    'dataLabel.excludeEmpty': '、空行は除外',
    'dataLabel.scrollToEdit': 'スクロールして編集可能',
    'dataLabel.editLabel': 'データ名（編集可能）',
    'dataLabel.originalData': '元データ',
    'dataLabel.column': '列',
    'dataLabel.placeholder': 'データ名を入力',
    'dataLabel.edited': '編集済',
    'dataLabel.original': '元',
    'dataLabel.hintsTitle': '使い方のヒント',
    'dataLabel.hint1': 'データ名が複数列に分散している場合、開始列と終了列を指定してください',
    'dataLabel.hint2': '例: C列とD列にデータ名がある → 開始列:3、終了列:4',
    'dataLabel.hint3': '各行で、指定範囲内の空でないセルが自動的に結合されます',
    'dataLabel.hint4': '結合は半角スペースで連結されます（例: "個人" + "2000万円未満" → "個人 2000万円未満"）',
    'dataLabel.hint5': 'プレビュー表のデータ名は直接編集できます（自動結合された名前を手動で調整可能）',
    'dataLabel.hint6': 'データ名が1列のみの場合は「スキップ」を押してください',
    'dataLabel.checkSettings': '設定を確認してください',
    'dataLabel.confirm': 'この設定で続ける',
    'dataLabel.skip': 'スキップ',
    'dataLabel.returnToStart': '最初に戻る',
    
    // UnitSettings
    'unit.title': '単位とスケールの設定',
    'unit.description': '軸の値に表示する単位とスケールを設定します。',
    'unit.xAxis': 'X軸（横軸）の設定',
    'unit.yAxis': 'Y軸（縦軸）の設定',
    'unit.unitType': '単位の種類',
    'unit.specificUnit': '具体的な単位',
    'unit.unit': '単位',
    'unit.scale': 'スケール',
    'unit.customUnit': 'カスタム単位',
    'unit.prefix': '接頭辞',
    'unit.suffix': '接尾辞',
    'unit.prefixPlaceholder': '例：約',
    'unit.suffixPlaceholder': '例：以上',
    'unit.useComma': '数値にカンマを使用',
    'unit.decimalPlaces': '小数点以下の桁数',
    'unit.previewTitle': '表示プレビュー',
    'unit.previewLabel': 'サンプル値：',
    'unit.preview': 'プレビュー',
    'unit.dataValue': 'データ値',
    'unit.display': '表示',
    'unit.showAdvanced': '詳細設定を表示',
    'unit.hideAdvanced': '詳細設定を隠す',
    'unit.confirm': 'この設定で続ける',
    'unit.skip': '単位を設定しない',
    'unit.selectUnitType': '単位の種類を選択',
    'unit.selectUnit': '単位を選択',
    'unit.selectScale': 'スケールを選択',
    'unit.scaleInfo': 'スケール設定について',
    'unit.scaleExample': 'スケールを設定すると、グラフの軸の値が調整されます。例：データが「1000000」の場合、スケールを「百万」に設定すると軸には「1」と表示されます。',
    'unit.next': '次へ：グラフタイトルの設定',
    'unit.back': '前に戻る',
    'unit.returnToStart': '最初に戻る',
    // Unit type labels
    'unit.type.currency': '通貨',
    'unit.type.weight': '重量',
    'unit.type.count': '数量',
    'unit.type.percentage': '割合',
    'unit.type.none': '単位なし',
    // Currency units
    'unit.currency.yen': '¥',
    'unit.currency.dollar': '$',
    'unit.currency.euro': '€',
    // Weight units
    'unit.weight.kg': 'kg',
    'unit.weight.t': 't',
    'unit.weight.g': 'g',
    // Count units
    'unit.count.people': '人',
    'unit.count.items': '個',
    'unit.count.units': '件',
    // Percentage units
    'unit.percentage.percent': '%',
    // None
    'unit.none.none': 'なし',
    // Scale labels
    'unit.scale.1': 'そのまま',
    'unit.scale.10': '十 (10)',
    'unit.scale.100': '百 (100)',
    'unit.scale.1000': '千 (1,000)',
    'unit.scale.10000': '万 (10,000)',
    'unit.scale.100000': '十万 (100,000)',
    'unit.scale.1000000': '百万 (1,000,000)',
    'unit.scale.10000000': '千万 (10,000,000)',
    'unit.scale.100000000': '億 (100,000,000)',
    'unit.scale.1000000000': '十億 (1,000,000,000)',
    'unit.scale.10000000000': '百億 (10,000,000,000)',
    'unit.scale.100000000000': '千億 (100,000,000,000)',
    
    // ChartTitleSettings
    'chartTitle.title': 'グラフタイトルの設定',
    'chartTitle.description': 'グラフ全体を表す名前を設定してください。この名前はグラフの凡例に表示されます。',
    'chartTitle.aboutTitle': 'グラフタイトルについて',
    'chartTitle.barLine': '棒グラフ・折れ線グラフ: 上部の凡例に表示されます',
    'chartTitle.pie': '円グラフ: 右側の凡例タイトルとして表示されます',
    'chartTitle.emptyDefault': '空欄の場合はデフォルト（縦軸のヘッダー名）が使用されます',
    'chartTitle.label': 'グラフタイトル',
    'chartTitle.placeholder': '例： {default}',
    'chartTitle.default': 'デフォルト： {default}',
    'chartTitle.previewTitle': '表示プレビュー',
    'chartTitle.tipsTitle': '使い方のヒント',
    'chartTitle.tip1': 'データ内容を簡潔に表す名前がおすすめ',
    'chartTitle.tip2': '空欄のままでもOK（自動でデフォルト名が使われます）',
    'chartTitle.tip3': '後からでも変更可能です',
    'chartTitle.confirm': 'グラフを表示する',
    'chartTitle.back': '前に戻る',
    'chartTitle.returnToStart': '最初に戻る',
    
    // フッター
    'footer.terms': '利用規約',
    'footer.privacy': 'プライバシーポリシー',
    'footer.legal': '特定商取引法に基づく表記',
    'footer.copyright': '© 2025 Grafico. All rights reserved.',
    
    // エラーメッセージ
    'error.fileType': 'CSVファイルを選択してください',
    'error.network': 'ネットワークエラーが発生しました',
  },
  
  en: {
    // Header
    'menu.open': 'Open menu',
    'menu.title': 'Menu',
    'menu.updates': 'Updates',
    'menu.pricing': 'Pricing',
    'menu.howToUse': 'How to Use',
    'menu.faq': 'FAQ',
    'menu.comingSoon': 'Coming Soon',
    'menu.myPage': 'My Page',
    'menu.logout': 'Logout',
    'menu.login': 'Login',
    'menu.signup': 'Sign Up',
    'menu.plan': 'Plan',
    
    // Common
    'common.goBack': 'Go Back',
    'common.returnToStart': 'Return to Start',
    
    // Axis Selection
    'axis.title': 'Axis Settings',
    'axis.description': 'Select columns to use for the horizontal axis (X-axis) and vertical axis (Y-axis) of the chart',
    'axis.xAxisLabel': 'Horizontal Axis (X-axis)',
    'axis.yAxisLabel': 'Vertical Axis (Y-axis)',
    'axis.selectColumn': 'Select column',
    'axis.dataPreview': 'Data Preview (First 3 rows)',
    'axis.next': 'Next: Set Units and Scale',
    
    // Home Page
    'home.title': 'Create Charts from Data Easily',
    'home.subtitle': 'Upload a CSV file and generate beautiful charts in seconds',
    'home.uploadButton': 'Upload CSV File',
    'home.orDragDrop': 'or drag and drop',
    'home.reset': 'Reset',
    'home.download': 'Download',
    'home.analyzing': 'Analyzing...',
    'home.resetDialog.title': 'Discard Settings?',
    'home.resetDialog.description': 'This will discard all current settings and return to the beginning. This action cannot be undone.',
    'home.resetDialog.cancel': 'Cancel',
    'home.resetDialog.ok': 'OK',
    
    // FileUpload
    'upload.title': 'Upload File',
    'upload.description': 'Upload a CSV or Excel file',
    'upload.dropzone': 'Drop file here',
    'upload.or': 'or',
    'upload.selectFile': 'Select File',
    'upload.loading': 'Loading...',
    'upload.error': 'Error',
    'upload.sampleData': 'Use Sample Data',
    'upload.backToHome': 'Back to Home',
    'upload.supportedFormats': 'Supported formats: CSV, Excel (.xlsx, .xls)',
    'upload.maxSize': 'Max size: 10MB',
    'upload.sampleDataTitle': 'Example of Optimal Data Structure for Charts',
    'upload.sampleDataDescription': 'See the example below to understand what file format works best for smooth chart creation.',
    'upload.showSampleData': 'Show Sample Data',
    'upload.hideSampleData': 'Hide Sample Data',
    'upload.recommendedFormat': 'Recommended Data Structure Example',
    'upload.sheetsFound': 'sheets found',
    'upload.sheet': 'Sheet',
    'upload.rowsOfData': 'rows of data',
    'upload.delete': 'Delete',
    'upload.processing': 'Processing file...',
    
    // ChartDisplay
    'chart.title': 'Chart',
    'chart.barChart': 'Bar Chart',
    'chart.lineChart': 'Line Chart',
    'chart.pieChart': 'Pie Chart',
    'chart.downloadImage': 'Download Chart',
    'chart.reconfigure': 'Reconfigure',
    'chart.reset': 'Reset',
    'chart.showDataLabels': 'Show data values on chart',
    'chart.labelSize': 'Label Size',
    'chart.smaller': 'Smaller',
    'chart.larger': 'Larger',
    'chart.settings': 'Settings',
    'chart.display': 'Display',
    'chart.selectType': 'Select Chart Type',
    'chart.selectDescription': 'Choose the best chart format for your data',
    'chart.dataLabels': 'Data Value Display',
    'chart.dataLabelsDescription': 'Display data values on the chart. This will also be reflected when downloading.',
    'chart.generatedChart': 'Generated Chart',
    'chart.dataPoints': 'data points',
    'chart.dataSummary': 'Data Summary',
    'chart.dataCount': 'Count',
    'chart.maximum': 'Maximum',
    'chart.minimum': 'Minimum',
    'chart.average': 'Average',
    'chart.median': 'Median',
    'chart.backToHome': 'Back to Home',
    'chart.auto': 'Auto',
    'chart.labelOverlapWarning': '💡 Labels may overlap when there are many data points',
    
    // ChartInsights (AI解説)
    'insights.title': 'AI Insights',
    'insights.description': 'Ask AI about trends and characteristics in your chart data',
    'insights.freeLimit': '(Free Plan: 5 times/day)',
    'insights.standardLimit': '(50 times/day)',
    'insights.proLimit': '(Unlimited)',
    'insights.proUnlimited': 'Pro - Unlimited',
    'insights.upgradeTitle': 'Expand Usage Limits with Upgrade',
    'insights.currentLimit': 'Current limit: 5 times/day',
    'insights.upgradeDescription': 'Standard plan: 50 times/day, Pro plan: unlimited usage.',
    'insights.viewPlans': 'View Plans',
    'insights.remainingUsage': 'Today\'s remaining usage',
    'insights.unlimited': 'Unlimited usage available',
    'insights.questionLabel': 'Ask a question about your chart',
    'insights.questionPlaceholder': 'Example: Tell me about the trends in this data. Why is the difference between maximum and minimum values so large?',
    'insights.submitHint': 'Press Enter to submit, Shift+Enter for new line',
    'insights.characterCount': 'characters',
    'insights.analyzing': 'Analyzing...',
    'insights.getInsights': 'Get AI Insights',
    'insights.error': 'Error',
    'insights.resultTitle': 'AI Insights Result',
    'insights.notesTitle': '💡 Usage Notes',
    'insights.noteUnlimited': 'Pro members can use this feature unlimited times',
    'insights.noteDailyLimit': 'Up to {limit} uses per day',
    'insights.noteReset': 'Usage count resets daily at midnight (JST)',
    'insights.noteAccuracy': 'AI responses are for reference only and complete accuracy is not guaranteed',
    
    // Authentication (AuthModal)
    'auth.title': 'Account',
    'auth.description': 'Login or sign up',
    'auth.loginTab': 'Login',
    'auth.signupTab': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name (Optional)',
    'auth.namePlaceholder': 'John Doe',
    'auth.passwordConfirm': 'Confirm Password',
    'auth.passwordPlaceholder': '12+ characters with letters, numbers & symbols',
    'auth.passwordConfirmPlaceholder': 'Re-enter password',
    'auth.passwordRequirements': '12+ characters including uppercase, lowercase, numbers, and symbols (!@#$, etc.)',
    'auth.loggingIn': 'Logging in...',
    'auth.loginButton': 'Login',
    'auth.registering': 'Registering...',
    'auth.signupButton': 'Sign Up',
    'auth.forgotPassword': 'Forgot password?',
    'auth.or': 'or',
    'auth.googleLogin': 'Login with Google',
    'auth.googleSignup': 'Sign up with Google',
    'auth.error.emailInUse': 'This email address is already registered',
    'auth.error.invalidEmail': 'Invalid email format',
    'auth.error.userNotFound': 'User not found',
    'auth.error.wrongPassword': 'Incorrect password',
    'auth.error.weakPassword': 'Password must be 12+ characters with letters, numbers and symbols',
    'auth.error.popupClosed': 'Login was cancelled',
    'auth.error.recentLoginRequired': 'Re-login required',
    'auth.error.invalidCredential': 'Current password is incorrect',
    'auth.error.userDisabled': 'This account has been disabled',
    'auth.error.tooManyRequests': 'Too many requests. Please try again later',
    'auth.error.default': 'An error occurred. Please try again',
    'auth.error.passwordMismatch': 'Passwords do not match',
    'auth.error.passwordInvalid': 'Password must meet the following requirements: {errors}',
    
    // Pricing
    'pricing.pageTitle': 'Make Chart Creation More Comfortable',
    'pricing.pageSubtitle': 'Choose the plan that\'s right for you',
    'pricing.monthly': 'Monthly',
    'pricing.yearly': 'Yearly',
    'pricing.yearlyBadge': 'Save',
    'pricing.perMonth': '/month',
    'pricing.yearlyTotal': 'Annual ¥{price} ({savings}% off)',
    'pricing.popularChoice': '{percent}% of users choose this',
    'pricing.perDay': '≈ Only ¥{price}/day',
    'pricing.processing': 'Processing...',
    'pricing.currentPlan': 'Current Plan',
    'pricing.getStartedFree': 'Get Started Free',
    'pricing.upgrade': 'Upgrade',
    'pricing.planFree': 'Free',
    'pricing.planStandard': 'Standard',
    'pricing.planPro': 'Pro',
    'pricing.descFree': 'Start creating charts',
    'pricing.descStandard': 'Serious chart analysis',
    'pricing.descPro': 'For professionals',
    'pricing.badgePopular': 'Most Popular',
    'pricing.feature.filesFree': 'File storage: Up to 3',
    'pricing.feature.filesStandard': 'File storage: Up to 10',
    'pricing.feature.filesPro': 'File storage: Unlimited',
    'pricing.feature.aiFree': 'AI Insights: 5/month',
    'pricing.feature.aiStandard': 'AI Insights: 50/month',
    'pricing.feature.aiPro': 'AI Insights: Unlimited',
    'pricing.feature.basicCharts': 'Basic chart creation',
    'pricing.feature.allCharts': 'All chart features',
    'pricing.feature.communitySupport': 'Community support',
    'pricing.feature.prioritySupport': 'Priority support',
    'pricing.feature.dataExport': 'Data export',
    'pricing.feature.apiAccess': 'API Access',
    'pricing.feature.apiAccessSoon': 'API Access (Coming Soon)',
    'pricing.faqTitle': 'Frequently Asked Questions',
    'pricing.faq1.question': 'Can I change my plan anytime?',
    'pricing.faq1.answer': 'Yes, you can change or cancel your plan at any time. Plan changes take effect immediately.',
    'pricing.faq2.question': 'What are AI Insights?',
    'pricing.faq2.answer': 'AI analyzes your chart data and automatically suggests trends, characteristics, and improvements.',
    'pricing.faq3.question': 'Can I start with the free plan?',
    'pricing.faq3.answer': 'Of course! Try our service with the free plan first, and upgrade when you need to.',
    'pricing.error.loginRequired': 'Please register for an account first',
    'pricing.error.priceIdNotFound': 'Price ID not found',
    'pricing.error.checkoutFailed': 'An error occurred: {message}',
    'pricing.error.paymentFailed': 'Failed to create payment page. Please try again.',
    
    // Pricing
    'pricing.title': 'Pricing Plans',
    
    // MyPage
    'mypage.title': 'My Page',
    'mypage.subtitle': 'Account information and plan details',
    'mypage.paymentSuccess.title': '🎉 Payment Completed!',
    'mypage.paymentSuccess.description': 'Your upgrade to a paid plan is complete. All features are now available.',
    'mypage.profile.title': 'Profile',
    'mypage.profile.description': 'Basic account information',
    'mypage.profile.username': 'Username',
    'mypage.profile.notSet': 'Not set',
    'mypage.profile.email': 'Email Address',
    'mypage.profile.registeredDate': 'Registered Date',
    'mypage.profile.unknown': 'Unknown',
    'mypage.plan.title': 'Current Plan',
    'mypage.plan.description': 'Your active plan information',
    'mypage.plan.label': 'Plan',
    'mypage.plan.free': 'Free Plan',
    'mypage.plan.standard': 'Standard Plan',
    'mypage.plan.pro': 'Pro Plan',
    'mypage.plan.premium': 'Premium Plan',
    'mypage.plan.upgrade': 'Upgrade to Paid Plan',
    'mypage.plan.freeInfo': 'The <strong>Free Plan</strong> gives you access to basic features. Upgrade to a paid plan to unlock:',
    'mypage.plan.feature1': 'High-resolution chart exports',
    'mypage.plan.feature2': 'Custom theme creation',
    'mypage.plan.feature3': 'Unlimited data storage',
    'mypage.plan.feature4': 'Priority support',
    'mypage.settings.title': 'Account Settings',
    'mypage.settings.description': 'Manage your account',
    'mypage.settings.editProfile': 'Edit Profile',
    'mypage.settings.changePassword': 'Change Password',
    'mypage.settings.googleUserNote': 'Google users cannot change password',
    'mypage.settings.deleteAccount': 'Delete Account',
    
    // UpdatesPage
    'updates.title': 'Updates',
    'updates.9.title': 'Implemented English Language Switch Feature',
    'updates.9.description': "Support was added for switching between Japanese and English. I learned that considering differences in word order, it's better to have the translation data define each language's natural word order, with the component simply passing values.",
    'updates.8.title': 'Added Terms of Service, Privacy Policy, Legal Notice, and Google Analytics',
    'updates.8.description': 'In preparation for moving to Stripe production environment, we created Terms of Service and Privacy Policy. Now ready to officially offer paid plans. Updated Legal Notice with latest information. Introduced Google Analytics for access analysis. Renamed files to PrivacyPage.jsx and TermsPage.jsx to avoid ad blocker blocking.',
    'updates.7.title': 'Implemented AI Insights Feature',
    'updates.7.description': 'Added AI-powered analysis for charts and uploaded spreadsheet files as a premium feature. Setting up API permissions and building test servers was challenging, but glad it works now. Pricing page coming soon.',
    'updates.6.title': 'Implemented Account Deletion and Chart Data Value Display',
    'updates.6.description': 'You can now safely delete your account from My Page. Two-step confirmation and re-authentication prevent accidental deletions. Also added ability to display data values on bar and line charts. Font size automatically adjusts based on data count, with manual fine-tuning available. Remember to force reload when external systems are involved...',
    'updates.5.title': 'Fixed Minor Inconveniences',
    'updates.5.description': 'Fixed issue where data orientation couldn\'t be changed when selecting header range with column-oriented data. Now you can create charts even when data is arranged horizontally.',
    'updates.4.title': 'Support for Data with Parentheses',
    'updates.4.description': 'You can now create charts while preserving parentheses in data. Also fixed the issue where downloaded charts had transparent backgrounds making them hard to see - now downloads with white background.',
    'updates.3.title': 'Implemented Login Feature',
    'updates.3.description': 'Using Firebase Authentication, you can now log in with email address or Google account.',
    'updates.2.title': 'Added Slider for Better Chart Visibility & Changed Chart Colors to Steel Blue Base',
    'updates.2.description': 'Making charts more visible.',
    'updates.1.title': 'Created Updates Page',
    'updates.1.description': 'You can now view app update history in timeline format.',
    
    // DataRangeSelector
    'dataRange.titleData': 'Select Data Range',
    'dataRange.titleHeader': 'Select Column Header Range',
    'dataRange.descriptionData': 'Specify the range of data you want to chart. The highlighted area in blue will be selected.',
    'dataRange.descriptionHeader': 'Specify the range containing column headers (item names). Include all rows if they span multiple rows.',
    'dataRange.startRow': 'Start Row',
    'dataRange.endRow': 'End Row',
    'dataRange.startCol': 'Start Column',
    'dataRange.endCol': 'End Column',
    'dataRange.rangeInfo': 'Selected Range:',
    'dataRange.rowCol': '{rows} rows × {cols} columns',
    'dataRange.preview': 'Data Preview',
    'dataRange.row': 'Row',
    'dataRange.showMore': 'Show More ({count} rows remaining)',
    'dataRange.confirmData': 'Create Chart with This Range',
    'dataRange.confirmHeader': 'Use This Range as Column Headers',
    'dataRange.backToStart': 'Back to Start',
    
    // SheetSelector
    'sheet.title': 'Select Sheet',
    'sheet.description': 'This file contains multiple sheets. Select the sheet containing the data you want to chart.',
    'sheet.available': 'Available Sheets ({count})',
    'sheet.number': 'Sheet {num}',
    'sheet.selected': 'Selected:',
    'sheet.confirm': 'Continue with This Sheet',
    'sheet.back': 'Go Back',
    
    // HeaderRangeSelector
    'headerRange.title': 'Select Header Range',
    'headerRange.description': 'You can specify multi-row headers. Headers in each column will be automatically merged.',
    'headerRange.headerStart': 'Header Start Row',
    'headerRange.headerEnd': 'Header End Row',
    'headerRange.dataStart': 'Data Start Row',
    'headerRange.rangeInfo': 'Header Range: Row {start} to Row {end} ({count} rows)',
    'headerRange.dataInfo': 'Data Range: From row {start} onwards',
    'headerRange.previewTitle': 'Header and Data Preview',
    'headerRange.editHeaders': 'Edit Header Names',
    'headerRange.editNote': 'Click to edit header names',
    'headerRange.editWarning': 'Auto-generated header names can be freely edited. Please review and correct if headers span multiple rows.',
    'headerRange.column': 'Column {num}',
    'headerRange.edited': 'edited',
    'headerRange.original': 'Original',
    'headerRange.columnName': ' name',
    'headerRange.dataRows': 'Data Rows',
    'headerRange.previewLabel': 'Preview (first 5 rows)',
    'headerRange.previewNote': 'Adjust settings to show preview',
    'headerRange.hintsTitle': 'Usage Tips',
    'headerRange.hint1': 'If headers span multiple rows, specify the end row',
    'headerRange.hint2': 'Headers in each column will be automatically merged within the specified range',
    'headerRange.hint3': 'Data start row must be after header end row',
    'headerRange.hint4': 'Example: Horizontal axis "Year", Vertical axis "Births", Headers end at row 2, Data starts at row 3',
    'headerRange.confirm': 'Continue with These Settings',
    'headerRange.warningMultiRow': 'Multiple header rows will be merged',
    'headerRange.clickToEdit': 'Click to edit',
    'headerRange.editButton': 'Edit Headers',
    'headerRange.emptyWarningTitle': 'Empty headers found',
    'headerRange.emptyWarningMessage': 'Some headers are empty. Please review and edit.',
    'headerRange.checkSettings': 'Please check settings',
    'headerRange.returnToStart': 'Return to Start',
    
    // DataOrientationSelector
    'orientation.title': 'Check Data Orientation',
    'orientation.description': 'Verify whether categories (item names) are arranged horizontally or vertically. You can transpose (swap rows and columns) as needed.',
    'orientation.original': 'Original',
    'orientation.transposed': 'Transposed',
    'orientation.previewOriginal': 'Original Data Preview',
    'orientation.previewTransposed': 'Transposed Preview',
    'orientation.infoOriginal': 'Categories: Vertical(current)',
    'orientation.infoTransposed': 'Categories: Horizontal(after transpose)',
    'orientation.confirmOriginal': 'Continue with Original',
    'orientation.confirmTransposed': 'Transpose and Continue',
    'orientation.previewNotice': '* Showing first 5 rows only',
    'orientation.selectionHintsTitle': '💡 Selection Tips',
    'orientation.hintOriginal': 'Original: When row 1 contains item names (year, month, etc.) and row 2+ contains data',
    'orientation.hintTransposed': 'Transposed: When column 1 contains item names and column 2+ contains data',
    
    // ParenthesesInterpretationSelector
    'parentheses.title': 'How to Interpret Parenthesized Numbers',
    'parentheses.description': 'Your data contains numbers enclosed in parentheses. Choose what these parentheses mean.',
    'parentheses.examplesTitle': 'Detected Parenthesized Numbers',
    'parentheses.optionPositive': 'Parentheses are decorative (treat as positive values)',
    'parentheses.optionNegative': 'Parentheses indicate negatives (treat as negative values)',
    'parentheses.previewTitle': 'Conversion Preview',
    'parentheses.previewOriginal': 'Original Value',
    'parentheses.previewConverted': 'After Conversion',
    'parentheses.confirm': 'Continue with These Settings',
    
    // SeparateHeaderSelector
    'separateHeader.title': 'Check Column Header Position',
    'separateHeader.description': 'Are the column headers (item names) in a separate location from the data body?',
    'separateHeader.guideTitle': 'When to choose "Yes"?',
    'separateHeader.guideExample': 'Example: In statistical tables where column headers (number of salary earners, salary amount, etc.) are at the top, followed by multiple data sections like "By Year" or "By Business Scale" arranged vertically.',
    'separateHeader.guideNote': 'Select "Yes" if you want to create a chart for a specific section (e.g., By Business Scale only).',
    'separateHeader.selectedRange': 'Selected Data Body Range',
    'separateHeader.rows': 'Rows: {start} 〜 {end} ({count} rows)',
    'separateHeader.cols': 'Columns: {start} 〜 {end} ({count} columns)',
    'separateHeader.no': 'No, they are in the same location',
    'separateHeader.yes': 'Yes, they are in a separate location',
    
    // DataLabelRangeSelector
    'dataLabel.title': 'Select Data Label Column(s)',
    'dataLabel.description': 'Specify the column(s) containing names (labels) for each data row. Multiple columns will be merged.',
    'dataLabel.aboutTitle': 'About This Step',
    'dataLabel.aboutText1': 'Use this when row labels are split across multiple columns',
    'dataLabel.aboutExample': 'Example: Column C contains "Individual", "Under 20M yen"; Column D contains "Other Corporations", "Total", etc.',
    'dataLabel.aboutText2': 'Non-empty cells within the specified column range will be automatically merged',
    'dataLabel.aboutText3': 'If labels are in a single column, please skip this step',
    'dataLabel.guide': 'What are label columns?',
    'dataLabel.guideText': 'Columns containing names that identify each data row.',
    'dataLabel.example': 'Examples: prefecture names, product names, dates, category names, etc.',
    'dataLabel.autoMerge': 'Non-empty values within the specified range will be automatically merged',
    'dataLabel.skipNote': 'If labels are in a single column only, press "Skip"',
    'dataLabel.labelStart': 'Label Start Column',
    'dataLabel.labelEnd': 'Label End Column',
    'dataLabel.columnRange': 'Valid range',
    'dataLabel.headerName': 'Merged Header Name',
    'dataLabel.headerPlaceholder': 'e.g., Region',
    'dataLabel.headerNote': 'Used in chart legends, etc.',
    'dataLabel.rangeInfo': 'Label Column Range: Column {start} to Column {end} ({count} columns)',
    'dataLabel.rowCount': 'Data Rows: {count} rows',
    'dataLabel.manualEdit': 'Manual edits: ',
    'dataLabel.rowsEdited': ' rows',
    'dataLabel.autoMergeNote': 'Non-empty values within the selected range will be automatically merged',
    'dataLabel.previewTitle': 'Merged Label Preview (All {count} rows, empty rows excluded)',
    'dataLabel.excludeEmpty': ', empty rows excluded',
    'dataLabel.scrollToEdit': 'Scroll to edit',
    'dataLabel.editLabel': 'Label (Editable)',
    'dataLabel.originalData': 'Original Data',
    'dataLabel.column': 'Column ',
    'dataLabel.placeholder': 'Enter label',
    'dataLabel.edited': 'edited',
    'dataLabel.original': 'Original',
    'dataLabel.hintsTitle': 'Usage Tips',
    'dataLabel.hint1': 'If labels are spread across multiple columns, specify start and end columns',
    'dataLabel.hint2': 'Example: Labels in columns C and D → Start: 3, End: 4',
    'dataLabel.hint3': 'For each row, non-empty cells within the specified range will be automatically merged',
    'dataLabel.hint4': 'Merging is done with spaces (Example: "Individual" + "Under 20M" → "Individual Under 20M")',
    'dataLabel.hint5': 'Labels in the preview table can be directly edited (auto-merged names can be manually adjusted)',
    'dataLabel.hint6': 'If labels are in a single column only, press "Skip"',
    'dataLabel.checkSettings': 'Please check settings',
    'dataLabel.confirm': 'Continue with These Settings',
    'dataLabel.skip': 'Skip Label Column',
    'dataLabel.returnToStart': 'Return to Start',
    
    // UnitSettings
    'unit.title': 'Unit and Scale Settings',
    'unit.description': 'Configure units and scales to display on axis values.',
    'unit.xAxis': 'X-Axis (Horizontal) Settings',
    'unit.yAxis': 'Y-Axis (Vertical) Settings',
    'unit.unitType': 'Unit Type',
    'unit.specificUnit': 'Specific Unit',
    'unit.unit': 'Unit',
    'unit.scale': 'Scale',
    'unit.customUnit': 'Custom Unit',
    'unit.prefix': 'Prefix',
    'unit.suffix': 'Suffix',
    'unit.prefixPlaceholder': 'e.g., approx.',
    'unit.suffixPlaceholder': 'e.g., or more',
    'unit.useComma': 'Use comma in numbers',
    'unit.decimalPlaces': 'Decimal places',
    'unit.previewTitle': 'Display Preview',
    'unit.previewLabel': 'Sample value:',
    'unit.preview': 'Preview',
    'unit.dataValue': 'Data value',
    'unit.display': 'Display',
    'unit.showAdvanced': 'Show Advanced Settings',
    'unit.hideAdvanced': 'Hide Advanced Settings',
    'unit.confirm': 'Continue with These Settings',
    'unit.skip': 'Skip Unit Settings',
    'unit.selectUnitType': 'Select unit type',
    'unit.selectUnit': 'Select unit',
    'unit.selectScale': 'Select scale',
    'unit.scaleInfo': 'About Scale Settings',
    'unit.scaleExample': 'Setting a scale adjusts axis values on the chart. Example: If data is "1000000" and scale is set to "million", the axis will show "1".',
    'unit.next': 'Next: Chart Title Settings',
    'unit.back': 'Go Back',
    'unit.returnToStart': 'Return to Start',
    // Unit type labels
    'unit.type.currency': 'Currency',
    'unit.type.weight': 'Weight',
    'unit.type.count': 'Count',
    'unit.type.percentage': 'Percentage',
    'unit.type.none': 'No Unit',
    // Currency units
    'unit.currency.yen': '¥',
    'unit.currency.dollar': '$',
    'unit.currency.euro': '€',
    // Weight units
    'unit.weight.kg': 'kg',
    'unit.weight.t': 't',
    'unit.weight.g': 'g',
    // Count units
    'unit.count.people': 'People',
    'unit.count.items': 'Items',
    'unit.count.units': 'Units',
    // Percentage units
    'unit.percentage.percent': '%',
    // None
    'unit.none.none': 'None',
    // Scale labels
    'unit.scale.1': 'As is',
    'unit.scale.10': 'Ten (10)',
    'unit.scale.100': 'Hundred (100)',
    'unit.scale.1000': 'Thousand (1,000)',
    'unit.scale.10000': 'Ten thousand (10,000)',
    'unit.scale.100000': 'Hundred thousand (100,000)',
    'unit.scale.1000000': 'Million (1,000,000)',
    'unit.scale.10000000': 'Ten million (10,000,000)',
    'unit.scale.100000000': 'Hundred million (100,000,000)',
    'unit.scale.1000000000': 'Billion (1,000,000,000)',
    'unit.scale.10000000000': 'Ten billion (10,000,000,000)',
    'unit.scale.100000000000': 'Hundred billion (100,000,000,000)',
    
    // ChartTitleSettings
    'chartTitle.title': 'Chart Title Settings',
    'chartTitle.description': 'Set a name that represents the entire chart. This name will be displayed in the chart legend.',
    'chartTitle.aboutTitle': 'About Chart Titles',
    'chartTitle.barLine': 'Bar/Line Charts: Displayed in top legend',
    'chartTitle.pie': 'Pie Charts: Displayed as legend title on the right',
    'chartTitle.emptyDefault': 'Empty field uses default (vertical axis header name)',
    'chartTitle.label': 'Chart Title',
    'chartTitle.placeholder': 'e.g., {default}',
    'chartTitle.default': 'Default: {default}',
    'chartTitle.previewTitle': 'Display Preview',
    'chartTitle.tipsTitle': 'Usage Tips',
    'chartTitle.tip1': 'Use a concise name that represents the data content',
    'chartTitle.tip2': 'Empty field is OK (default name will be used automatically)',
    'chartTitle.tip3': 'Can be changed later',
    'chartTitle.confirm': 'Show Graph',
    'chartTitle.back': 'Go Back',
    'chartTitle.returnToStart': 'Return to Start',
    
    // Footer
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.legal': 'Legal Notice',
    'footer.copyright': '© 2025 Grafico. All rights reserved.',
    
    // Error messages
    'error.fileType': 'Please select a CSV file',
    'error.network': 'A network error occurred',
  }
}
